### PR TITLE
feat: set-up front-end workflow

### LINKED ISSUE #8: [FEATURE] set-up front-end workflow
**Using parcel-bundler**
setting up the front-end workflow using parcel,eslint and prettier to configure React-js library

### PR DESCRIPTION
**Pull request by cmcWebCode40**
i was able to configure javascript framework(react)into our project directory using eslint and parcel, without breaking any default setup.
fixes #8

## Description
I used parcel and installed some eslint plugins to work with reactjs
Fixes #8 

## How I Tested my code.
I tested my code using the default scripts for linting the code

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jibrinmasud — DISMISSED** [review]

**Review by jibrinmasud — DISMISSED** [review]
Reviewed

**Review by syflex — DISMISSED** [review]

**Review by okezieobi — DISMISSED** [review]
Nice work

**Review by jibrinmasud — APPROVED** [review]
Done.

**Review by syflex — APPROVED** [review]

**Comment by cmcWebCode40** [comment]
switching the project starter file

**Pull request closed without merging**
