### PR TITLE
Ch project setup v2

### PR DESCRIPTION
**Pull request by okezieobi**
## Description
Refactored project

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by cmcWebCode40 — COMMENTED** [review]
Failed codacy test😔

**Review by cmcWebCode40 — COMMENTED** [review]
@okezieobi  i have reviewed your code here is the link to the issues
just the css file and server/package.json
[codacy-error](https://app.codacy.com/gh/BuildForSDG/Team-062-yourRight/pullRequest?prid=5474712)

**Review by cmcWebCode40 — COMMENTED** [review]
@okezieobi  all checks passed except for server/package.json 
here is the error message [codacy-erro](https://app.codacy.com/gh/BuildForSDG/Team-062-yourRight/pullRequest?prid=5474712)

**Comment by okezieobi** [comment]
> @okezieobi all checks passed except for server/package.json
> here is the error message [codacy-erro](https://app.codacy.com/gh/BuildForSDG/Team-062-yourRight/pullRequest?prid=5474712)

Sending a push now, Codacy sucks!!!!

**Review by cmcWebCode40 — COMMENTED** [review]
This codacy checks i dont understand 
there are 2 extra error is that server/paackge.json file
link.. [codacy-error](https://app.codacy.com/gh/BuildForSDG/Team-062-yourRight/pullRequest?prid=5474712).
try linting the code locally before pushing you will need to install those maybe
you cant lint json files

**Review by cmcWebCode40 — DISMISSED** [review]
bro can you delete that server/package.json file it has just one error now
lets merge this folder?

>1. JSON is not sorted  in that file

{
Nothing like commenting in package.json, I am deleting al offenders

**Comment by cmcWebCode40** [comment]
> bro can you delete that server/package.json file it has just one error now
> lets merge this folder?
> 
> > 1. JSON is not sorted  in that file
> 
> {
> Nothing like commenting in package.json, I am deleting al offenders

still displaying the same error!!!

**Comment by okezieobi** [comment]
If this thing does not work I may delete this branch and call it a day

**Comment by okezieobi** [comment]
As it wont allow backend package,json

**Comment by cmcWebCode40** [comment]
> As it wont allow backend package,.son
still the same problem maybe is something on can just google to know the problem

**Pull request closed without merging**
